[project]
name = "mcp-server"
version = "0.1.0"
description = "MCP server for healthcare booking API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.8.0",
    "httpx>=0.28.0",
]
