# Generated by Django 4.2.10 on 2025-06-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="telegram_id",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
    ]
